{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2019-6442",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://dumpco.re/blog/ntpsec-bugs",
          "name": "https://dumpco.re/blog/ntpsec-bugs",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://dumpco.re/bugs/ntpsec-authed-oobwrite",
          "name": "https://dumpco.re/bugs/ntpsec-authed-oobwrite",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://github.com/ntpsec/ntpsec/blob/NTPsec_1_1_3/NEWS",
          "name": "https://github.com/ntpsec/ntpsec/blob/NTPsec_1_1_3/NEWS",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://www.exploit-db.com/exploits/46178/",
          "name": "46178",
          "refsource": "EXPLOIT-DB",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue was discovered in NTPsec before 1.1.3. An authenticated attacker can write one byte out of bounds in ntpd via a malformed config request, related to config_remotely in ntp_config.c, yyparse in ntp_parser.tab.c, and yyerror in ntp_parser.y."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2019-01-16T05:29Z",
  "lastModifiedDate": "2019-01-17T11:29Z"
}